dist: bionic
language: ruby
rvm: 2.7
before_install:
  - export LIBTORCH_VERSION=1.6.0
  - ./test/ci/install_libtorch.sh
  - bundle config build.torch-rb --with-torch-dir=$HOME/libtorch/$LIBTORCH_VERSION
cache:
  bundler: true
  directories:
    - $HOME/libtorch
    - $HOME/data
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
